language: node_js
sudo: enabled

node_js:
- "8"

install:
- npm install

//tests whether the code is working properly or not
//change to '- npm run test'  to execute the unit tests via Karma.
//change to '- npm run e2e'   to execute the end-to-end tests via Protractor.
script:
- npm run build
